#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mnemonic {
    // System
    Syscall, Sysenter, Sysexit, Ret, Nop, Int3, Hlt,
    
    // Stack
    Push, Pop,
    
    // Data movement
    Mov, Movsx, Movzx, Lea, Xchg,
    
    // Arithmetic
    Add, Sub, Mul, Imul, Div, Idiv, Inc, Dec, Neg, Not,
    
    // Logical
    Xor, And, Or,
    
    // Compare/Test
    Cmp, Test,
    
    // Control flow
    Jmp, Call, Je, Jne, Jz, Jnz, Jg, Jge, Jl, Jle, Ja, Jb,
    
    // Conditional moves
    Cmove, Cmovne, Cmovz, Cmovnz, Cmovg, Cmovge, Cmovl, Cmovle,
    Cmova, Cmovae, Cmovb, Cmovbe, Cmovs, Cmovns,
    
    // Flags
    Clc, Stc, Cli, Sti, Cld, Std, Cmc,
    Pushfq, Popfq,
    
    // Shifts/Rotates
    Shl, Shr, Sal, Sar, Rol, Ror, Rcl, Rcr,
    
    // Bit operations
    Bt, Bts, Btr, Btc,
    Bsf, Bsr, Popcnt, Lzcnt, Tzcnt,
    
    // String operations
    Movsb, Movsw, Movs, Movsq,
    Cmpsb, Cmpsw, Cmpsd, Cmpsq,
    Scasb, Scasw, Scasd, Scasq,
    Stosb, Stosw, Stosd, Stosq,
    Lodsb, Lodsw, Lodsd, Lodsq,
    
    // Memory fencing
    Mfence, Lfence, Sfence,
    
    // Prefetch
    Prefetch, Prefetchnta, Prefetcht0, Prefetcht1, Prefetcht2, Prefetchw,
    
    // SIMD
    Movaps, Movapd, Movups, Movupd,
    Movss, Movsd,
    Addps, Addpd, Addss, Addsd,
    Subps, Subpd, Subss, Subsd,
    Mulps, Mulpd, Mulss, Mulsd,
    Divps, Divpd, Divss, Divsd,
    Sqrtps, Sqrtpd, Sqrtss, Sqrtsd,
    
    // AVX
    Vaddps, Vaddpd, Vsubps, Vsubpd,
    Vmulps, Vmulpd, Vdivps, Vdivpd,
    Vmovaps, Vmovapd, Vmovss, Vmovsd,
    Vmovdqa, Vmovdqu, Vmovdqa32, Vmovdqa64,
    Vpaddd, Vpsubd, Vpmulld, Vpand, Vpor, Vpxor,
    
    // Stack frame
    Enter, Leave,
    
    // Other
    Cpuid, Rdtsc,
}

impl Mnemonic {
    pub fn from_str(s: &str) -> Option<Self> {
        use Mnemonic::*;
        match s {
            "syscall" => Some(Syscall),
            "sysenter" => Some(Sysenter),
            "sysexit" => Some(Sysexit),
            "ret" => Some(Ret),
            "nop" => Some(Nop),
            "int3" => Some(Int3),
            "hlt" => Some(Hlt),
            "cpuid" => Some(Cpuid),
            "rdtsc" => Some(Rdtsc),
            "push" => Some(Push),
            "pop" => Some(Pop),
            "mov" => Some(Mov),
            "movsx" => Some(Movsx),
            "movzx" => Some(Movzx),
            "lea" => Some(Lea),
            "xchg" => Some(Xchg),
            "add" => Some(Add),
            "sub" => Some(Sub),
            "mul" => Some(Mul),
            "imul" => Some(Imul),
            "div" => Some(Div),
            "idiv" => Some(Idiv),
            "inc" => Some(Inc),
            "dec" => Some(Dec),
            "neg" => Some(Neg),
            "not" => Some(Not),
            "xor" => Some(Xor),
            "and" => Some(And),
            "or" => Some(Or),
            "cmp" => Some(Cmp),
            "test" => Some(Test),
            "jmp" => Some(Jmp),
            "call" => Some(Call),
            "je" | "jz" => Some(Je),
            "jne" | "jnz" => Some(Jne),
            "jg" => Some(Jg),
            "jge" => Some(Jge),
            "jl" => Some(Jl),
            "jle" => Some(Jle),
            "ja" => Some(Ja),
            "jb" => Some(Jb),
            "cmove" | "cmovz" => Some(Cmove),
            "cmovne" | "cmovnz" => Some(Cmovne),
            "cmovg" => Some(Cmovg),
            "cmovge" => Some(Cmovge),
            "cmovl" => Some(Cmovl),
            "cmovle" => Some(Cmovle),
            "cmova" => Some(Cmova),
            "cmovae" => Some(Cmovae),
            "cmovb" => Some(Cmovb),
            "cmovbe" => Some(Cmovbe),
            "cmovs" => Some(Cmovs),
            "cmovns" => Some(Cmovns),
            "clc" => Some(Clc),
            "stc" => Some(Stc),
            "cli" => Some(Cli),
            "sti" => Some(Sti),
            "cld" => Some(Cld),
            "std" => Some(Std),
            "cmc" => Some(Cmc),
            "pushfq" => Some(Pushfq),
            "popfq" => Some(Popfq),
            "shl" | "sal" => Some(Shl),
            "shr" => Some(Shr),
            "sar" => Some(Sar),
            "rol" => Some(Rol),
            "ror" => Some(Ror),
            "rcl" => Some(Rcl),
            "rcr" => Some(Rcr),
            "bt" => Some(Bt),
            "bts" => Some(Bts),
            "btr" => Some(Btr),
            "btc" => Some(Btc),
            "bsf" => Some(Bsf),
            "bsr" => Some(Bsr),
            "popcnt" => Some(Popcnt),
            "lzcnt" => Some(Lzcnt),
            "tzcnt" => Some(Tzcnt),
            "movsb" => Some(Movsb),
            "movsw" => Some(Movsw),
            "movsd" => Some(Movsd),
            // "movsd" => Some(Movs),
            "movsq" => Some(Movsq),
            "cmpsb" => Some(Cmpsb),
            "cmpsw" => Some(Cmpsw),
            "cmpsd" => Some(Cmpsd),
            "cmpsq" => Some(Cmpsq),
            "scasb" => Some(Scasb),
            "scasw" => Some(Scasw),
            "scasd" => Some(Scasd),
            "scasq" => Some(Scasq),
            "stosb" => Some(Stosb),
            "stosw" => Some(Stosw),
            "stosd" => Some(Stosd),
            "stosq" => Some(Stosq),
            "lodsb" => Some(Lodsb),
            "lodsw" => Some(Lodsw),
            "lodsd" => Some(Lodsd),
            "lodsq" => Some(Lodsq),
            "mfence" => Some(Mfence),
            "lfence" => Some(Lfence),
            "sfence" => Some(Sfence),
            "prefetch" => Some(Prefetch),
            "prefetchnta" => Some(Prefetchnta),
            "prefetcht0" => Some(Prefetcht0),
            "prefetcht1" => Some(Prefetcht1),
            "prefetcht2" => Some(Prefetcht2),
            "prefetchw" => Some(Prefetchw),
            "movaps" => Some(Movaps),
            "movapd" => Some(Movapd),
            "movups" => Some(Movups),
            "movupd" => Some(Movupd),
            "movss" => Some(Movss),
            "addps" => Some(Addps),
            "addpd" => Some(Addpd),
            "addss" => Some(Addss),
            "addsd" => Some(Addsd),
            "subps" => Some(Subps),
            "subpd" => Some(Subpd),
            "subss" => Some(Subss),
            "subsd" => Some(Subsd),
            "mulps" => Some(Mulps),
            "mulpd" => Some(Mulpd),
            "mulss" => Some(Mulss),
            "mulsd" => Some(Mulsd),
            "divps" => Some(Divps),
            "divpd" => Some(Divpd),
            "divss" => Some(Divss),
            "divsd" => Some(Divsd),
            "sqrtps" => Some(Sqrtps),
            "sqrtpd" => Some(Sqrtpd),
            "sqrtss" => Some(Sqrtss),
            "sqrtsd" => Some(Sqrtsd),
            "vaddps" => Some(Vaddps),
            "vaddpd" => Some(Vaddpd),
            "vsubps" => Some(Vsubps),
            "vsubpd" => Some(Vsubpd),
            "vmulps" => Some(Vmulps),
            "vmulpd" => Some(Vmulpd),
            "vdivps" => Some(Vdivps),
            "vdivpd" => Some(Vdivpd),
            "vmovaps" => Some(Vmovaps),
            "vmovapd" => Some(Vmovapd),
            "vmovss" => Some(Vmovss),
            "vmovsd" => Some(Vmovsd),
            "vmovdqa" => Some(Vmovdqa),
            "vmovdqu" => Some(Vmovdqu),
            "vmovdqa32" => Some(Vmovdqa32),
            "vmovdqa64" => Some(Vmovdqa64),
            "vpaddd" => Some(Vpaddd),
            "vpsubd" => Some(Vpsubd),
            "vpmulld" => Some(Vpmulld),
            "vpand" => Some(Vpand),
            "vpor" => Some(Vpor),
            "vpxor" => Some(Vpxor),
            "enter" => Some(Enter),
            "leave" => Some(Leave),
            _ => None,
        }
    }
}

impl core::fmt::Display for Mnemonic {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Syscall => "syscall",
            Self::Sysenter => "sysenter",
            Self::Sysexit => "sysexit",
            Self::Ret => "ret",
            Self::Nop => "nop",
            Self::Int3 => "int3",
            Self::Hlt => "hlt",
            Self::Cpuid => "cpuid",
            Self::Push => "push",
            Self::Pop => "pop",
            Self::Mov => "mov",
            Self::Movsx => "movsx", 
            Self::Movzx => "movzx",
            Self::Lea => "lea",
            Self::Xchg => "xchg",
            Self::Add => "add",
            Self::Sub => "sub",
            Self::Mul => "mul",
            Self::Imul => "imul",
            Self::Div => "div",
            Self::Idiv => "idiv",
            Self::Inc => "inc",
            Self::Dec => "dec",
            Self::Neg => "neg",
            Self::Not => "not",
            Self::Xor => "xor",
            Self::And => "and",
            Self::Or => "or",
            Self::Cmp => "cmp",
            Self::Test => "test",
            Self::Jmp => "jmp",
            Self::Call => "call",
            Self::Je => "je",
            Self::Jne => "jne",
            Self::Jz => "jz",
            Self::Jnz => "jnz",
            Self::Jg => "jg",
            Self::Jge => "jge",
            Self::Jl => "jl",
            Self::Jle => "jle",
            Self::Ja => "ja",
            Self::Jb => "jb",
            Self::Cmove => "cmove",
            Self::Cmovne => "cmovne",
            Self::Cmovz => "cmovz",
            Self::Cmovnz => "cmovnz",
            Self::Cmovg => "cmovg",
            Self::Cmovge => "cmovge",
            Self::Cmovl => "cmovl",
            Self::Cmovle => "cmovle",
            Self::Cmova => "cmova",
            Self::Cmovae => "cmovae",
            Self::Cmovb => "cmovb",
            Self::Cmovbe => "cmovbe",
            Self::Cmovs => "cmovs",
            Self::Cmovns => "cmovns",
            Self::Clc => "clc",
            Self::Stc => "stc",
            Self::Cli => "cli",
            Self::Sti => "sti",
            Self::Cld => "cld",
            Self::Std => "std",
            Self::Cmc => "cmc",
            Self::Pushfq => "pushfq",
            Self::Popfq => "popfq",
            Self::Shl => "shl",
            Self::Shr => "shr",
            Self::Sal => "sal",
            Self::Sar => "sar",
            Self::Rol => "rol",
            Self::Ror => "ror",
            Self::Rcl => "rcl",
            Self::Rcr => "rcr",
            Self::Bt => "bt",
            Self::Bts => "bts",
            Self::Btr => "btr",
            Self::Btc => "btc",
            Self::Bsf => "bsf",
            Self::Bsr => "bsr",
            Self::Popcnt => "popcnt",
            Self::Lzcnt => "lzcnt",
            Self::Tzcnt => "tzcnt",
            Self::Movsb => "movsb",
            Self::Movsw => "movsw",
            Self::Movs => "movs",
            Self::Movsq => "movsq",
            Self::Cmpsb => "cmpsb",
            Self::Cmpsw => "cmpsw",
            Self::Cmpsd => "cmpsd",
            Self::Cmpsq => "cmpsq",
            Self::Scasb => "scasb",
            Self::Scasw => "scasw",
            Self::Scasd => "scasd",
            Self::Scasq => "scasq",
            Self::Stosb => "stosb",
            Self::Stosw => "stosw",
            Self::Stosd => "stosd",
            Self::Stosq => "stosq",
            Self::Lodsb => "lodsb",
            Self::Lodsw => "lodsw",
            Self::Lodsd => "lodsd",
            Self::Lodsq => "lodsq",
            Self::Mfence => "mfence",
            Self::Lfence => "lfence",
            Self::Sfence => "sfence",
            Self::Prefetch => "prefetch",
            Self::Prefetchnta => "prefetchnta",
            Self::Prefetcht0 => "prefetcht0",
            Self::Prefetcht1 => "prefetcht1",
            Self::Prefetcht2 => "prefetcht2",
            Self::Prefetchw => "prefetchw",
            Self::Movaps => "movaps",
            Self::Movapd => "movapd",
            Self::Movups => "movups",
            Self::Movupd => "movupd",
            Self::Movss => "movss",
            Self::Movsd => "movsd",
            Self::Addps => "addps",
            Self::Addpd => "addpd",
            Self::Addss => "addss",
            Self::Addsd => "addsd",
            Self::Subps => "subps",
            Self::Subpd => "subpd",
            Self::Subss => "subss",
            Self::Subsd => "subsd",
            Self::Mulps => "mulps",
            Self::Mulpd => "mulpd",
            Self::Mulss => "mulss",
            Self::Mulsd => "mulsd",
            Self::Divps => "divps",
            Self::Divpd => "divpd",
            Self::Divss => "divss",
            Self::Divsd => "divsd",
            Self::Sqrtps => "sqrtps",
            Self::Sqrtpd => "sqrtpd",
            Self::Sqrtss => "sqrtss",
            Self::Sqrtsd => "sqrtsd",
            Self::Vaddps => "vaddps",
            Self::Vaddpd => "vaddpd",
            Self::Vsubps => "vsubps",
            Self::Vsubpd => "vsubpd",
            Self::Vmulps => "vmulps",
            Self::Vmulpd => "vmulpd",
            Self::Vdivps => "vdivps",
            Self::Vdivpd => "vdivpd",
            Self::Vmovaps => "vmovaps",
            Self::Vmovapd => "vmovapd",
            Self::Vmovss => "vmovss",
            Self::Vmovsd => "vmovsd",
            Self::Vmovdqa => "vmovdqa",
            Self::Vmovdqu => "vmovdqu",
            Self::Vmovdqa32 => "vmovdqa32",
            Self::Vmovdqa64 => "vmovdqa64",
            Self::Vpaddd => "vpaddd",
            Self::Vpsubd => "vpsubd",
            Self::Vpmulld => "vpmulld",
            Self::Vpand => "vpand",
            Self::Vpor => "vpor",
            Self::Vpxor => "vpxor",
            Self::Enter => "enter",
            Self::Leave => "leave",
            Self::Rdtsc => "rdtsc",
        };
        write!(f, "{}", s)
    }
}
