[package]
name = "debugger-present"
version = "0.0.1"
authors = ["Jozef Podlecki"]
edition = "2018"
rust-version = "1.84"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_System_Diagnostics_Debug"
]