[book]
authors = ["Jozef Podlecki"]
language = "en"
multilingual = false
src = "src"
title = "Reverse Engineering Exercises"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/Jozefpodlecki/reverse-engineering-exercises"