
name: Deploy to GH Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: jetli/trunk-action@v0.5.1
        with:
          version: "latest"
      - run: |
          rustup target add wasm32-unknown-unknown
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npx @tailwindcss/cli -i ./styles/main.css -o ./styles/output.css --minify 
      - run: trunk build --release
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v4
        with:
          path: "./dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v5
        id: deployment