name: Publish docs

on:
  workflow_dispatch:

jobs:
  update_docs:
    name: Publish docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-mdbook@v1
      - run: |
          cd docs
          mdbook build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book 